# -*- coding: utf-8 -*-
"""
Created on Sat Mar  7 18:11:23 2020

@author: Kyra
"""

import tkinter as tk
import vulcan2
window = tk.Tk()
var_states = []
def checkbox_data():
    var_states.append(var1.get())
    var_states.append(var2.get())
    var_states.append(var3.get())
    var_states.append(var4.get())
    var_states.append(var5.get())
    var_states.append(var6.get())
    var_states.append(var7.get())
    var_states.append(var8.get())
    var_states.append(var9.get())
    var_states.append(var10.get())
    var_states.append(var11.get())
    var_states.append(var12.get())
    var_states.append(var13.get())
    var_states.append(var14.get())
    var_states.append(var15.get())
    var_states.append(var16.get())
    var_states.append(var17.get())
    var_states.append(var18.get())
    var_states.append(var19.get())
    var_states.append(var20.get())
    var_states.append(var21.get())
    var_states.append(var22.get())
    var_states.append(var23.get())
    var_states.append(var24.get())
    var_states.append(var25.get())
    var_states.append(var26.get())
    var_states.append(var27.get())
    w = tk.StringVar(window)
    tk.Label(window, textvariable=w).pack()
    choice = vulcan2.choose(var_states)
    w.set(choice)
window.title('OptimizedDisney')
window.geometry('500x800')
l = tk.Label(window, bg='white', width=80, text='Select the rides you want to go on')
l.pack()
var1 = tk.IntVar()
var2 = tk.IntVar()
var3 = tk.IntVar()
var4 = tk.IntVar()
var5 = tk.IntVar()
var6 = tk.IntVar()
var7 = tk.IntVar()
var8 = tk.IntVar()
var9 = tk.IntVar()
var10 = tk.IntVar()
var11 = tk.IntVar()
var12 = tk.IntVar()
var13 = tk.IntVar()
var14 = tk.IntVar()
var15 = tk.IntVar()
var16 = tk.IntVar()
var17 = tk.IntVar()
var18 = tk.IntVar()
var19 = tk.IntVar()
var20 = tk.IntVar()
var21 = tk.IntVar()
var22 = tk.IntVar()
var23 = tk.IntVar()
var24 = tk.IntVar()
var25 = tk.IntVar()
var26 = tk.IntVar()
var27 = tk.IntVar()
c1 = tk.Checkbutton(window, text='Astro Orbiter',variable=var1, onvalue=1, offvalue=0)
c1.pack()
c2 = tk.Checkbutton(window, text='The Barnstormer',variable=var2, onvalue=1, offvalue=0)
c2.pack()
c3 = tk.Checkbutton(window, text='Big Thunder Mountain Railroad',variable=var3, onvalue=1, offvalue=0)
c3.pack()
c4 = tk.Checkbutton(window, text='Buzz Lightyear\'s Space Ranger Spin',variable=var4, onvalue=1, offvalue=0)
c4.pack()
c5 = tk.Checkbutton(window, text='Walt Disney\'s Carosel of Progress',variable=var5, onvalue=1, offvalue=0)
c5.pack()
c6 = tk.Checkbutton(window, text='Country Bear Jamboree',variable=var6, onvalue=1, offvalue=0)
c6.pack()
c7 = tk.Checkbutton(window, text='Dumbo the Flying Elephant',variable=var7, onvalue=1, offvalue=0)
c7.pack()
c8 = tk.Checkbutton(window, text='Walt Disney\'s Enchanted Tiki Room',variable=var8, onvalue=1, offvalue=0)
c8.pack()
c9 = tk.Checkbutton(window, text='The Hall of Presidents',variable=var9, onvalue=1, offvalue=0)
c9.pack()
c10 = tk.Checkbutton(window, text='Haunted Mansion',variable=var10, onvalue=1, offvalue=0)
c10.pack()
c11 = tk.Checkbutton(window, text='it\'s a small world',variable=var11, onvalue=1, offvalue=0)
c11.pack()
c12 = tk.Checkbutton(window, text='Jungle Cruise',variable=var12, onvalue=1, offvalue=0)
c12.pack()
c13 = tk.Checkbutton(window, text='Liberty Square Riverboat',variable=var13, onvalue=1, offvalue=0)
c13.pack()
c14 = tk.Checkbutton(window, text='Mad Tea Party',variable=var14, onvalue=1, offvalue=0)
c14.pack()
c15 = tk.Checkbutton(window, text='The Magic Carpets of Aladdin',variable=var15, onvalue=1, offvalue=0)
c15.pack()
c16 = tk.Checkbutton(window, text='The Many Adventures of Winnie the Pooh',variable=var16, onvalue=1, offvalue=0)
c16.pack()
c17 = tk.Checkbutton(window, text='Mickey\'s PhilharMagic',variable=var17, onvalue=1, offvalue=0)
c17.pack()
c18 = tk.Checkbutton(window, text='Monsters, Inc. Laugh Floor',variable=var18, onvalue=1, offvalue=0)
c18.pack()
c19 = tk.Checkbutton(window, text='Peter Pan\'s Flight',variable=var19, onvalue=1, offvalue=0)
c19.pack()
c20 = tk.Checkbutton(window, text='Pirates of the Caribbean',variable=var20, onvalue=1, offvalue=0)
c20.pack()
c21 = tk.Checkbutton(window, text='Prince Charming Regal Carrousel',variable=var21, onvalue=1, offvalue=0)
c21.pack()
c22 = tk.Checkbutton(window, text='Seven Dwarfs Mine Train',variable=var22, onvalue=1, offvalue=0)
c22.pack()
c23 = tk.Checkbutton(window, text='Space Mountain',variable=var23, onvalue=1, offvalue=0)
c23.pack()
c24 = tk.Checkbutton(window, text='Splash Mountain',variable=var24, onvalue=1, offvalue=0)
c24.pack()
c25 = tk.Checkbutton(window, text='Tomorrowland Speedway',variable=var25, onvalue=1, offvalue=0)
c25.pack()
c26 = tk.Checkbutton(window, text='Tomorrowland Transit Authority PeopleMover',variable=var26, onvalue=1, offvalue=0)
c26.pack()
c27 = tk.Checkbutton(window, text='Under the Sea - Journey of The Little Mermaid',variable=var27, onvalue=1, offvalue=0)
c27.pack()
button = tk.Button(window, text="Compute", width=30, command=checkbox_data)
button.pack()
window.mainloop()
      

      

 
